name: Azure Function CI/CD mit Staging Integrationstests

on:
  workflow_dispatch: # Ermöglicht manuelles Auslösen

env:
  AZURE_FUNCTIONAPP_NAME: 'your-function-app-name' # Ersetzen Sie dies durch den Namen Ihrer Function App
  RESOURCE_GROUP_NAME: 'your-resource-group' # Ersetzen Sie dies durch den Namen Ihrer Ressourcengruppe
  STAGING_SLOT_NAME: 'staging' # Name Ihres Staging-Slots

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Staging # Verknüpfung mit der Staging-Umgebung
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4
#
# ---- Ab hier relevant
#
  
