name: wait for azure function

on:
  workflow_dispatch: # Ermöglicht manuelles Auslösen

env:
  TEST_VAR: 'test123'

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
     - name: teststes
       run: |
        echo $TEST_VAR {{ $TEST_VAR }}
        echo ""test""
